### PR TITLE
Build on Darwin

### PR DESCRIPTION
**Pull request by deployable**
Add test for apple and to skip getline definition
Add memrchr function in apple detection

### CODE REVIEW

**Comment by pjps** [comment]
Hello Matt,

Thank you so much for this patch. Last weekend I did finally get to it. While the patch applied and built fine, looking more into it I realized that memrchr(3) was called only from common.c:gettimezone() routine. It did not feel right to add new definition of memrchr(3), just for that usage. Instead, I've updated gettimezone() to work without memrchr(3) - 51a7aeafa4.

About getline() definition: do you get any error while building with it? I doubt if the common.c definition is used under standard C environments. IIUC  initially getline() too was a GNU extension, but it's been standardised since then.

Thank you.

**Comment by deployable** [comment]
Hi. Removing memrchr makes sense. I was just trying to get things working =)

So the error for `getline()` when building on osx was: 
```
common.c:72:1: error: conflicting types for 'getline'
 getline (char **lineptr, ssize_t *n, FILE *stream)
 ^
In file included from common.c:28:0:
/usr/include/stdio.h:442:9: note: previous declaration of 'getline' was here
 ssize_t getline(char ** __restrict, size_t * __restrict, FILE * __restrict) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
         ^
```

It seems to work ok so far relying on the bsd version. 

There's probably [better solutions](http://stackoverflow.com/a/1117615/1318694)

**Comment by pjps** [comment]
Okay, getline() too has been expunged - 64d371b6f8. Initially it was problematic on FreeBSD machines. I hope it works now.

Thank you.

**Comment by deployable** [comment]
Cool, thanks.  Recent BSD should have it in `libc` now, same as osx.

**Comment by pjps** [comment]
Yes, true.

**Pull request closed without merging**
